#!/usr/bin/env bash

set -e
set -o pipefail

version=$(bosh2 int manifest/manifest.yml --path /stemcells/0/version)
name=bosh-${CPI}-ubuntu-trusty-go_agent

stemcell=$(curl -s "https://bosh.io/api/v1/stemcells/${name}?all=1" | \
               jq -c --arg version "${version}" '.[] | select(.version == $version)')

url=$(echo ${stemcell} | jq '.regular.url' )
sha1=$(echo ${stemcell} | jq '.regular.sha1' )

bosh2 upload-stemcell ${url} --version ${version} --name ${name} --sha1 ${sha1}
