#!/usr/bin/env bash

set -e

if [ -d bucc-state/state ]; then
    mv bucc-state/{vars.yml,state} bucc/ || true
fi

# Never skip deploy, needed for DR tests
if [ -f bucc/state/state.json ]; then
    jq '.current_manifest_sha = ""' bucc/state/state.json > state.json
    mv state.json bucc/state/state.json
fi

mkdir -p ${PWD}/bosh-cache/.bosh
rm -rf ${HOME}/.bosh
ln -s ${PWD}/bosh-cache/.bosh/ ${HOME}/.bosh

pushd bucc > /dev/null

echo "Bucc version"
./bin/bucc | head -n1

echo ${VARS} > "vars.yml"

./bin/bucc up ${ARGS}

popd > /dev/null

mv bucc/{vars.yml,state} bucc-state-out
