#!/usr/bin/env bash

cp -r bosh-cache/.bosh ${HOME} | true

pushd bucc > /dev/null

echo ${VARS} > "vars.yml"

./bin/bucc up ${ARGS}

popd > /dev/null

mv bucc/{vars.yml,state} bucc-state/

cp -r ${HOME}/.bosh bosh-cache
