---
resources:
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      branch: ((branch))

  # releases

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  # stemcells

  - name: ubuntu-xenial-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-xenial-go_agent
      version_family: '97.latest'

  # outputs

  - name: compiled-releases
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: ((aws_key_id))
      secret_access_key: ((aws_secret_access_key))
      regexp: ".*-(\\d+).tgz"

jobs:
  - name: compile-bosh-release-266
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-release
          version:
            version: "267.3.0"
        - get: ubuntu-xenial-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-xenial-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

