---
# resources {
resources:
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      branch: ((branch))

  # releases

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: uaa-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/uaa-release

  - name: credhub-release
    type: bosh-io-release
    source:
      repository: pivotal-cf/credhub-release

  - name: bpm-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bpm-release

  - name: backup-and-restore-sdk-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/backup-and-restore-sdk-release

  - name: warden-cpi
    type: bosh-io-release
    source:
      repository: cppforlife/bosh-warden-cpi-release

  - name: garden-linux
    type: bosh-io-release
    source:
      repository: cloudfoundry/garden-linux-release

  - name: garden-runc
    type: bosh-io-release
    source:
      repository: cloudfoundry/garden-runc-release

  - name: grootfs
    type: bosh-io-release
    source:
      repository: cloudfoundry/grootfs-release

  # stemcells

  - name: ubuntu-trusty-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version_family: '3586.latest'

  # outputs

  - name: compiled-releases
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: ((aws_key_id))
      secret_access_key: ((aws_secret_access_key))
      regexp: ".*-(\\d+).tgz"
# }
jobs:
  - name: compile-bosh-release-266
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-release
          version:
            version: "266.7.0"
        - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bosh-release-267
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-release
          version:
            version: "267.5.0"
        - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-57
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "57.3"
          - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-59
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "59"
          - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-60
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "60.2"
          - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"


  - name: compile-credhub-release-1.8
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: credhub-release
          version:
            version: "1.8.3"
        - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: credhub-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-credhub-release-1.7
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: credhub-release
          version:
            version: "1.7.1"
        - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: credhub-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-credhub-release-1.9
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: credhub-release
          version:
            version: "1.9.3"
        - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: credhub-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bpm-release-0.6.0
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bpm-release
          version:
            version: "0.6.0"
        - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bpm-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bpm-release-0.9.0
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bpm-release
          version:
            version: "0.9.0"
        - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bpm-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bbr-sdk-release-1.6
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: backup-and-restore-sdk-release
          version:
            version: "1.6.0"
        - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: backup-and-restore-sdk-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  # bosh-lite related

  - name: compile-warden-cpi
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: warden-cpi
            version:
              version: "40"
          - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: warden-cpi
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-garden-linux
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: garden-linux
            version:
              version: "0.342.0"
          - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: garden-linux
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-garden-runc-1-9
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: garden-runc
            version:
              version: "1.9.4"
          - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: garden-runc
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-grootfs
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: grootfs
            version:
              version: "0.24.0"
          - get: ubuntu-trusty-stemcell
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: grootfs
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
