instance_groups: []
name: compile-releases
releases:
- name: concourse
  sha1: e464cb907d7436a43f712b71d6dbde0fdce4be6d
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=7.3.2
  version: 7.3.2
- name: os-conf
  sha1: 78d79f08ff5001cc2a24f572837c7a9c59a0e796
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=18
  version: 18
- name: credhub-importer
  sha1: b8dcbe24ead72f3ca93747e0630e2f34c8b89cc4
  url: https://github.com/cloudfoundry-community/credhub-importer-boshrelease/releases/download/1.1.0/credhub-importer-1.1.0.tgz
  version: 1.1.0
- name: postgres
  sha1: e44bbe8f8a7cdde1cda67b202e399a239d104db6
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=43
  version: 43
- name: bucc-bbr
  url: git+https://github.com/starkandwayne/bucc-bbr-boshrelease
  version: 8
- name: vault-credhub-proxy
  sha1: 8038e8eb63b993a4c95e96924a88e4e3e6b251e5
  url: https://s3.amazonaws.com/vault-credhub-proxy-boshrelease/vault-credhub-proxy-release-1.1.9.tgz
  version: 1.1.9
- name: director-bosh-dns
  sha1: a365141b2204233fca76c6d97ca85ff6805e2b33
  url: https://github.com/starkandwayne/director-bosh-dns-release/releases/download/v0.1.0/director-bosh-dns-0.1.0.tgz
  version: 0.1.0
- name: bosh-dns
  sha1: d1aadbda5d60c44dec4a429cda872cf64f6d8d0b
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.10.0
  version: 1.10.0
stemcells:
- alias: large
  os: ubuntu-bionic
  version: "1.22"
update:
  canaries: 1
  canary_watch_time: 1000 - 90000
  max_in_flight: 1
  update_watch_time: 1000 - 90000
