instance_groups: []
name: compile-releases
releases:
- name: concourse
  sha1: 558aa18093dd1f7d32f3fbb668d49f47a33ad17c
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=5.0.0
  version: 5.0.0
- name: os-conf
  sha1: 78d79f08ff5001cc2a24f572837c7a9c59a0e796
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=18
  version: 18
- name: credhub-importer
  sha1: b8dcbe24ead72f3ca93747e0630e2f34c8b89cc4
  url: https://github.com/cloudfoundry-community/credhub-importer-boshrelease/releases/download/1.1.0/credhub-importer-1.1.0.tgz
  version: 1.1.0
- name: postgres
  sha1: 3dd10b417b21cfa3257f1cc891e9e46f02fefe16
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=36
  version: 36
- name: bucc-bbr
  url: git+https://github.com/starkandwayne/bucc-bbr-boshrelease
  version: 8
- name: vault-credhub-proxy
  url: git+https://github.com/starkandwayne/vault-credhub-proxy-release
  version: 1.1.4
- name: director-bosh-dns
  sha1: a365141b2204233fca76c6d97ca85ff6805e2b33
  url: https://github.com/starkandwayne/director-bosh-dns-release/releases/download/v0.1.0/director-bosh-dns-0.1.0.tgz
  version: 0.1.0
- name: bosh-dns
  sha1: d1aadbda5d60c44dec4a429cda872cf64f6d8d0b
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.10.0
  version: 1.10.0
- name: garden-runc
  sha1: 9fca045a0a90cf38cf79feabcc582efd5a20538e
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.19.1
  version: 1.19.1
stemcells:
- alias: large
  os: ubuntu-xenial
  version: "250.21"
update:
  canaries: 1
  canary_watch_time: 1000 - 90000
  max_in_flight: 1
  update_watch_time: 1000 - 90000
