#!/usr/bin/env bash

set -ex

function main() {
    source <(grep -v 'main $@' /usr/local/bin/start-bosh)

    source /etc/profile.d/chruby.sh
    chruby 2.3.1

    export OUTER_CONTAINER_IP=$(ruby -rsocket -e 'puts Socket.ip_address_list
                          .reject { |addr| !addr.ip? || addr.ipv4_loopback? || addr.ipv6? }
                          .map { |addr| addr.ip_address }')

    export DOCKER_HOST="tcp://${OUTER_CONTAINER_IP}:4243"

    local certs_dir
    certs_dir=$(mktemp -d)
    start_docker "${certs_dir}"

    docker network create -d bridge --subnet=10.245.0.0/16 director_network

    pushd bucc > /dev/null
    cat <<EOF > "vars.yml"
      director_name: docker
      docker_host: "${DOCKER_HOST}"
      docker_tls:
        ca: "$(cat ${certs_dir}/ca_json_safe.pem)"
        certificate: "$(cat ${certs_dir}/client_certificate_json_safe.pem)"
        private_key: "$(cat ${certs_dir}/client_private_key_json_safe.pem)"
      internal_cidr: 10.245.0.0/16
      internal_gw: 10.245.0.1
      internal_ip: 10.245.0.3
      network: director_network
EOF

    ./bin/bucc up --cpi docker

    popd > /dev/null
}

main
