---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-deployment
  - name: stemcell
  - name: release

outputs:
  - name: compiled-release

run:
  path: bosh-deployment/ci/compiled-releases/tasks/export-release.sh
