#!/usr/bin/env bash

set -e
set -o pipefail

pushd credhub-cli

tar zxvf credhub-linux*.tgz
chmod +x credhub*

export version=$(cat version)

popd

cp credhub-cli/credhub bucc/bin/

pushd bucc > /dev/null

if [[ -z $(git config --global user.email) ]]; then
    git config --global user.email "ci@starkandwayne.com"
fi
if [[ -z $(git config --global user.name) ]]; then
    git config --global user.name "CI Bot"
fi

# Ignore file permission changes
git config core.fileMode true

git status

echo "commit the latest gredhub-cli binary"
git add -f bin/credhub
git commit -m "updating credhub cli to $version"

popd > /dev/null

echo "CLONE repository"
git clone bucc bucc-out
