#!/usr/bin/env bash

set -e

if [ -d bucc-state/state ]; then
    mv bucc-state/{vars.yml,state} bucc/ || true
fi

# Never skip deploy, needed for DR tests
if [ -f bucc/state/state.json ]; then
    jq '.current_manifest_sha = ""' bucc/state/state.json > state.json
    mv state.json bucc/state/state.json
fi

cp -r bosh-cache/.bosh ${HOME} | true

pushd bucc > /dev/null

echo "==== Bucc version ===="
./bin/bucc | head -n1

echo "==== Creating vars file ===="
echo ${VARS} > "vars.yml"

echo "==== Creating offline tarball ===="
./bin/bucc offline ${ARGS}

# TODO: are we going to test  and use extract tarbal?

echo "==== Enable Firewall ===="
apt-get install -q -y ufw
ufw allow to 10.0.0.0/8
ufw allow out 53
ufw default deny outgoing
sed -i '/ok icmp codes for INPUT/a -A ufw-before-output -p icmp -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT' /etc/ufw/before.rules
sed -i '/ok icmp codes for INPUT/a -A ufw-before-output -p icmp -m state --state ESTABLISHED,RELATED -j ACCEPT' /etc/ufw/before.rules
ufw enable

echo "==== Run BUCC up ===="
./bin/bucc up


popd > /dev/null

mv bucc/{vars.yml,state} bucc-state-out

cp -r ${HOME}/.bosh bosh-cache
