#!/bin/bash

set -eu

VERSION=$(cat version/number)
if [[ ! -f bucc/ci/release_notes.md ]]; then
  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
  exit 1
fi

echo ${VERSION}                         > github/tag
echo "${RELEASE_NAME} v${VERSION}"      > github/name
mv bucc-ci/ci/release_notes.md          github/notes.md

cat > github/notification <<EOF
<!here> New ${RELEASE_NAME} v${VERSION} released!
EOF

# Commit changes
if [[ -z $(git config --global user.email) ]]; then
    git config --global user.email "ci@starkandwayne.com"
fi
if [[ -z $(git config --global user.name) ]]; then
    git config --global user.name "CI Bot"
fi

pushd bucc > /dev/null

sed -i "2s/version.*/version=\"${VERSION}\"/" bin/bucc

git merge --no-edit master
if [[ -n $(git status -s) ]]; then
    git add -A
    git commit -m "release: v${VERSION}"
fi
REF=$(git rev-parse HEAD)
popd > /dev/null

git clone bucc bucc-out

echo ${REF} > github/commit
