#!/bin/bash

set -eu

VERSION=$(cat version/number)

echo "v${VERSION}"                      > release/tag
echo "BUCC v${VERSION}"                 > release/name

cat > release/notification <<EOF
<!here> New BUCC v${VERSION} released!
EOF

git config --global user.email "ci@starkandwayne.com"
git config --global user.name "CI Bot"

pushd bucc > /dev/null

rm -f ci/release_notes.md

sed -i "s/.*bucc.*/bucc=$VERSION/" .versions

git add -A
git commit -m "release: v${VERSION}"

popd > /dev/null

pushd bucc-master > /dev/null

# merge develop into master
git pull ../bucc -X theirs --no-edit

popd > /dev/null

# clone master so we have an output
git clone bucc-master bucc-out-master

# clone develop for develop output
git clone bucc bucc-out-develop

pushd bucc-out-develop
# merge upstream develop and keep our changes (we have bumped versions)
git pull https://github.com/starkandwayne/bucc develop -X ours --no-edit
