#!/bin/bash

set -eu

VERSION=$(cat version/number)
if [[ ! -f bucc-ci/ci/release_notes.md ]]; then
  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
  exit 1
fi

echo "v${VERSION}"                      > github/tag
echo "BUCC v${VERSION}"                 > github/name
mv bucc-ci/ci/release_notes.md          github/notes.md

cat > github/notification <<EOF
<!here> New BUCC v${VERSION} released!
EOF

git config --global user.email "ci@starkandwayne.com"
git config --global user.name "CI Bot"

pushd bucc > /dev/null

rm ci/release_notes.md

sed -i "2s/version.*/version=\"${VERSION}\"/" bin/bucc

git add -A
git commit -m "release: v${VERSION}"

REF=$(git rev-parse HEAD)
popd > /dev/null

git clone bucc bucc-out
