#!/usr/bin/env bash

set -e
set -o pipefail

custom_notes=$(pwd)/bucc-ci/ci/release_notes.md
notes=$(pwd)/release-notes/notes.md

touch ${custom_notes}
cp ${custom_notes} ${notes}

get_releases() {
    ops_files=$(find ops -name '*.yml' -exec bosh2 int {} \; | grep -v -E '^null')
    ops_files=$(spruce json <(echo -e "ops:\n${ops_files}") | jq '.ops | map(select((.path | contains("/releases")) and .type == "replace"))')
    non_unique_releases=$(bosh2 int src/bosh-deployment/bosh.yml -o <(echo -e "${ops_files}"))
    spruce json <(echo -e "${non_unique_releases}") | jq -c -r -M '.releases | sort_by(.name) | unique_by(.name) | .[]'
}

get_stemcell_version() {
    get_releases | jq -s -r 'map(select(.url and (.url | contains("ubuntu")))) | .[0].url | capture("ubuntu[a-z\\-]+(?<version>[\\d\\.]+)") | .version'
}

release_paths=$(curl -s https://bosh.io/releases/ | grep '<a href="/releases/' | cut -d'"' -f2 | cut -d'?' -f1)
get_release_url() {
    # sort results to prefere cloudfoundry over cloudfoundry-{incubator,community}
    local release_path=$(echo -e "${release_paths}" | grep -E "/${1}$|/${1}-release$|/${1}-boshrelease$" | sort -n | tail -n 1)

    if [ ! -z "${release_path}" ]; then
        echo "https://bosh.io${release_path}?version=${2}"
    fi
}

pushd bucc-stable > /dev/null
stable_releases=$(get_releases)
stable_stemcell=$(get_stemcell_version)
popd > /dev/null

echo $stable_releases | jq '.name'

pushd bucc > /dev/null
new_releases=$(get_releases)
new_stemcell=$(get_stemcell_version)
popd > /dev/null

notes_releases=""
for release in $(echo ${new_releases} | jq -c '.'); do
    name=$(echo ${release} | jq -r '.name')
    version=$(echo ${release} | jq -r '.version')
    stable_version=$(echo ${stable_releases} | jq -s -r --arg name "${name}" '.[] | select(.name == $name).version')

    release_url=$(get_release_url ${name} ${version})
    if [ ! -z "${release_url}" ]; then
        notes_releases+="| ${name} | [${version}](${release_url}) |"
    else
        notes_releases+="| ${name} | ${version} |"
    fi

    if [[ "${version}" != "${stable_version}" ]]; then
        notes_releases+=" yes |\n"
    else
        notes_releases+=" no |\n"
    fi
done

if [ ! -z "${notes_releases}" ]; then
    echo "## Release updates:" >> ${notes}
    echo "| Name | Version | Changed |" >> ${notes}
    echo "| ---- | ------- | ------- |" >> ${notes}
    echo -e "${notes_releases}" >> ${notes}
fi

if [[ ${stemcell} != ${new_stemcell} ]]; then
    echo "## Stemcell update:" >> ${notes}
    stemcell_url="https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/stable-${new_stemcell}"
    echo -e "Bumped to [${new_stemcell}](${stemcell_url})" >> ${notes}
fi

cat ${notes}
