#!/usr/bin/env bash

set -e

mv bucc-state/{vars.yml,state} bucc/
source <(./bucc/bin/bucc env)
bucc fly && bucc credhub

set -x

if [ ! -f bucc/state/upgrade-test ]; then
    bosh2 -n update-config runtime --name=test <(echo "foo: bar")

    fly -t bucc set-pipeline -n -c bucc-ci/ci/assets/acceptance-pipeline.yml -p test

    credhub set --no-overwrite --name secret/ping --value pong --type value

    touch bucc/state/upgrade-test
else
    bosh2 config runtime --name=test | grep foo

    fly -t bucc get-pipeline -p test | grep test

    credhub get --name secret/ping | grep pong
fi
