#!/usr/bin/env bash

set -e
set -o pipefail

# if [[ ${compiled_release_url} != *"${version}"*"${stemcell_version}"* ]]; then
#     releases_in_s3=$(curl -s "https://s3-eu-west-1.amazonaws.com/bucc-compiled-releases/?prefix=${name}")
#     if [[ ${releases_in_s3} != *"${version}-ubuntu-trusty-${stemcell_version}"* ]]; then
#         releases_to_compile+="- $( echo ${release} | jq -c '.version = "latest"' )\n"
#     fi
# fi
