#!/usr/bin/env bash

set -e
set -o pipefail

# if [[ ${compiled_release_url} != *"${version}"*"${stemcell_version}"* ]]; then
#     releases_in_s3=$(curl -s "https://s3-eu-west-1.amazonaws.com/bucc-compiled-releases/?prefix=${name}")
#
#         releases_to_compile+="- $( echo ${release} | jq -c '.version = "latest"' )\n"
#     fi
# fi

pushd compiled-releases-in > /dev/null
manifest=$(pwd)/manifest.yml

stemcel_version=$(bosh2 ${manifest} --path /stemcells/0/version)

for name in $(spruce json ${manifest} | jq '.releases[].name'); do
    version=$(bosh2 ${manifest} --path /releases/name=${name}/version)
    releases_in_s3=$(curl -s "https://s3-eu-west-1.amazonaws.com/bucc-compiled-releases/?prefix=${name}")

    if [[ ${releases_in_s3} != *"${version}-ubuntu-trusty-${stemcell_version}"* ]]; then
        cp ${name}*.tgz ../compile-releases/
    fi
done
