- name: stemcell
  path: /resource_pools/name=vms/stemcell?
  type: replace
  value:
    sha1: be46ce4c54003c95122508026ec232d499f75e58
    url: https://storage.googleapis.com/bosh-core-stemcells/1.150/bosh-stemcell-1.150-warden-boshlite-ubuntu-bionic-go_agent.tgz
