- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    sha1: 03399bc99770da3c8790400bfe3f2c77332d8bd2
    url: https://bosh-core-stemcells.s3-accelerate.amazonaws.com/0.18/bosh-stemcell-0.18-warden-boshlite-ubuntu-bionic-go_agent.tgz
