- name: stemcell
  path: /resource_pools/name=vms/stemcell?
  type: replace
  value:
    sha1: 29924c051be9df9e6a9706b1504a9568b5130d92
    url: https://storage.googleapis.com/bosh-core-stemcells/1.90/bosh-stemcell-1.90-warden-boshlite-ubuntu-bionic-go_agent.tgz
