- name: stemcell
  path: /resource_pools/name=vms/stemcell?
  type: replace
  value:
    sha1: 6dfd3adfa3993dde7a67c32b8f37174dfc82693b
    url: https://storage.googleapis.com/bosh-core-stemcells/1.91/bosh-stemcell-1.91-warden-boshlite-ubuntu-bionic-go_agent.tgz
