#!/bin/bash -e

pushd bucc > /dev/null

version=$(bosh int src/bosh-deployment/bosh.yml \
               -o ops/cpis/vsphere/0-cpi.yml \
               --path /resource_pools/name=vms/stemcell/url | \
               cut -d'=' -f2
         )

popd > /dev/null

pushd bucc-stemcell > /dev/null

url="https://bosh.io/d/stemcells/bosh-${CPI}-ubuntu-trusty-go_agent?v=${version}"

echo "Downloading: ${url}"
curl -L -J -O https://bosh.io/d/stemcells/bosh-${CPI}-ubuntu-trusty-go_agent?v=${version}

echo "Downloaded: $(ls)"
