#!/bin/bash -e

pushd bucc > /dev/null

rm -r state && mkdir state
echo "virtualbox" > state/cpi
echo "true" > state/lite
version=$(./bin/bucc int --path /releases/name=bosh/url | cut -d'-' -f7 | rev | cut -c 5- | rev)

popd > /dev/null

pushd bucc-stemcell > /dev/null

url="https://bosh.io/d/stemcells/bosh-${CPI}-ubuntu-trusty-go_agent?v=${version}"

echo "Downloading: ${url}"
curl -L -J -O https://bosh.io/d/stemcells/bosh-${CPI}-ubuntu-trusty-go_agent?v=${version}

echo "Downloaded: $(ls)"
