#!/bin/bash -e

header() {
        echo
        echo "###############################################"
        echo
        echo $*
        echo
}

pushd bucc > /dev/null
header "Pulling in any git submodules..."
git submodule update --init --recursive --force

cat support_matrix.yml | while read config; do
    cpi=$(bosh int <(echo ${config}) --path /0/cpi)
    lite=$(bosh int <(echo ${config}) --path /0/lite)

    header "Manifest CPI: ${cpi} LITE: ${lite}"
    bosh int <(
         cat ops/cpis/${cpi}/vars.tmpl && \
         echo "director_name: bucc-ci" && \
         bosh int <(echo ${VARS})
    ) > vars.yml
    cat vars.yml | grep -v 'password\|secret\|key'

    rm -rf state && mkdir state
    echo ${lite} > state/lite
    echo ${cpi} > state/cpi

    manifest_name=${cpi}
    if [ ${lite} = "true" ]; then
       manifest_name+="-lite"
    fi

    ./bin/bucc int > ../bucc-generated-manifest/${manifest_name}.yml

    echo ""
    echo "bucc-generated-manifest/${manifest_name}.yml"
done
