---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: bosh-deployment

outputs:
  - name: bbl-state

params:
  BBL_GCP_SERVICE_ACCOUNT_KEY: replace-me
  BBL_IAAS: gcp
  BBL_GCP_REGION: replace-me

run:
  path: bosh-deployment/ci/tasks/bbl-up-bosh-lite-gcp.sh
