---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-deployment
  - name: stemcell

run:
  path: bosh-deployment/ci/tasks/test-main-bosh-docker.sh
