---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: bosh-deployment
  - name: bbl-state
  - name: stemcell

run:
  path: bosh-deployment/ci/tasks/test-bosh-lite-gcp.sh
