---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

params:
  UPDATING_BASE_MANIFEST: false
  FILE_TO_UPDATE: ~
  BOSH_IO_RELEASE: ~

inputs:
- name: bosh-deployment
- name: release
- name: stemcell

outputs:
- name: bosh-deployment
  path: bosh-deployment-output

run:
  path: bosh-deployment/ci/tasks/update-release.sh
