---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-deployment
  - name: cpi

params:
  CPI_OPS_FILE: ~
  CPI_NAME: ~
  GITHUB_RELEASE: false

outputs:
  - name: bosh-deployment
    path: bosh-deployment-output

run:
  path: bosh-deployment/ci/tasks/update-cpi.sh
