#!/usr/bin/env bash

set -e
set -o pipefail

pushd release-in > /dev/null

for package in $(ls packages); do
    if [[ ${PACKAGES} != *"${package}"* ]]; then
        rm -r packages/${package}
    fi
done

for job in $(ls jobs); do
    if [[ ${JOB_NAME} != ${job} ]]; then
        rm -r jobs/${job}
    fi
done

job_spec=$(spruce json jobs/${JOB_NAME}/spec)
bosh2 int <(echo ${job_spec} | jq --argjson pkgs "${PACKAGES}" '.packages |= map(. as $pkg | select(any($pkgs[]; . == $pkg)))') \
      > jobs/${JOB_NAME}/spec

git config --global user.email "ci@starkandwayne.com"
git config --global user.name "CI Bot"

git add -A
git commit -m "Removed unused jobs/packages" || echo "No changes to commit"

popd > /dev/null
git clone release-in release
