#!/usr/bin/env bash

set -e
set -o pipefail

pushd ${NAME}-cli

export version=$(cat version)

popd

pushd bucc > /dev/null

sed -i "s/.*${NAME}.*/${NAME}=$version/" .versions

if [[ -z $(git config --global user.email) ]]; then
    git config --global user.email "ci@starkandwayne.com"
fi
if [[ -z $(git config --global user.name) ]]; then
    git config --global user.name "CI Bot"
fi

git status

echo "commit the latest ${NAME}-cli to $version"
git add .versions
git commit -m "updating ${NAME} cli to $version"

popd > /dev/null

echo "CLONE repository"
git clone bucc bucc-out
