#!/usr/bin/env bash

set -e
set -o pipefail

pushd ${name}-cli

export version=$(cat version)

popd

pushd bucc > /dev/null

sed -i "s/.*${name}.*/${name}=$version/" .versions

if [[ -z $(git config --global user.email) ]]; then
    git config --global user.email "ci@starkandwayne.com"
fi
if [[ -z $(git config --global user.name) ]]; then
    git config --global user.name "CI Bot"
fi

git status

echo "commit the latest ${name}-cli to $version"
git add .versions
git commit -m "updating ${name} cli to $version"

popd > /dev/null

echo "CLONE repository"
git clone bucc bucc-out
